### ISSUE TITLE
infer variants in merged mode and compare to usearch -unoise3

### ISSUE THREAD

**Issue by jianshu93** [benjjneb/dada2#1310]
Dear Author,
I am wondering whether I can merge forward and reverse reads (after quality control of course) before doing error rate learning and variant inferring so that I can compare with usearch -unoise, which use a quite different error correction model. Why do you suggest variant inferring on both forward and reverse reads at the very first place?

Thanks,

Jianshu

**Comment by benjjneb** [comment]
See. e.g. https://github.com/benjjneb/dada2/issues/434

Merged reads often have a different relationship between the quality scores and the actual error rates in the overlapping and non-overlapping parts of the read.

**Comment by jianshu93** [comment]
Hello Benj,

I merged reads using usearch -fastq_mergepairs and it turns out that reads quality is not that different as you pointed out in #434.  The usearch merge algorithm paper is here: https://academic.oup.com/bioinformatics/article/31/21/3476/194979?login=true


Forward read quality and error rate in non-merge mode:

[FWD_read_plot.pdf](https://github.com/benjjneb/dada2/files/6250445/FWD_read_plot.pdf)
[Error_rates_per_sample_FWD.pdf](https://github.com/benjjneb/dada2/files/6250447/Error_rates_per_sample_FWD.pdf)

Reverse read quality and error rate in non-merge mode:
[REV_read_plot.pdf](https://github.com/benjjneb/dada2/files/6250450/REV_read_plot.pdf)
[Error_rates_per_sample_REV.pdf](https://github.com/benjjneb/dada2/files/6250451/Error_rates_per_sample_REV.pdf)


usearch merged reads quality and error rate (run dada2 in single end mode but using merged reads):
[MERGED_read_plot.pdf](https://github.com/benjjneb/dada2/files/6250457/MERGED_read_plot.pdf)
[Error_rates_per_sample_single.pdf](https://github.com/benjjneb/dada2/files/6250459/Error_rates_per_sample_single.pdf)

It looks like that the error rate with quality is still acceptable after using merged reads to learn the error model. 

In this case, if you agree we can then compare with usearch -unoise3 algorithm to over come a big challenge in having a lot of rare community when using pool mode in DADA2 (see here: http://fiererlab.org/2020/02/17/whats-in-a-number-estimating-microbial-richness-using-dada2/). 

I am comparing diversity metric and also ASVs using merged mode and pair end mode, and compare with usearch -unoise3. Do you have any suggestions?

Thank you,


Best

Jianshu

**Comment by jianshu93** [comment]
Another thing that surprises me is the removePrimer() function. I have mismatch error in the filterAndTrim() step if I do not use matchID=TRUE, but when I use it (no error), more than 2/3 of reads were dropped because of mismatch between forward and reverse reads. If I use cutadapt to do primer trimming, I can have the same size of non-primer reads file filtered as no-filter but primer trimmed when using removePrimer() function. See an attached screen shot of how many mismatch between forward and reverse reads if I use removePrimer() first and then  filterAndTrim() (have to use matchID = TRUE, otherwise filterAndTrim() keeps telling there are mismatches between forward and reverse reads). How does removePrimer() work? Why I have so many mismatches? see code using:

Fwd_pr="GTGCCAGCMGCCGCGGTAA"
Rvs_pr="GGACTACHVGGGTWTCTAAT"

filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))

fnFs.noprimer <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
fnRs.noprimer <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))

removePrimers(fnFs, fnFs.noprimer, primer.fwd=Fwd_pr, trim.fwd = TRUE,orient=TRUE, verbose=TRUE)
  removePrimers(fnRs, fnRs.noprimer, primer.fwd=Rvs_pr, trim.fwd = TRUE, orient=TRUE, verbose=TRUE)

filterAndTrim(fnFs.noprimer, filtFs, fnRs.noprimer, filtRs, truncLen=c(225,190),
              maxN=0, maxEE=c(1,2), truncQ=10, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE)

Can I filter separately for forward and reverse reads. I will still lose a lot of them when doing mergePair() right? I will still have problems when merge pair if I do no use matchID and filter forward and reverse reads at the same time right? I do not have this mismatch problem when using cutadapt before runnin dada2.



![Screen Shot 2021-04-02 at 12 47 18 PM](https://user-images.githubusercontent.com/38149286/113436276-6bfaea80-93b2-11eb-82fc-ee0a9b87f5ea.png)




Many thanks,

Jianshu

**Comment by benjjneb** [comment]
`removePrimers` is not recommended for Illumina data as it does not support paired-end reads, and there are other primer removal software, such as cutadapt or trimmomatic, that are more performant on such data.

The non-support for removing primers coherentely from paired-end reads is leading to the issue you are seeing. It is fixed by `matchID=TRUE` but still we don't recommend that approach for Illumina data.

**Comment by jianshu93** [comment]
What about the merge mode I mentioned above?

Thanks,

Jianshu

**Comment by benjjneb** [comment]
> What about the merge mode I mentioned above?

You can run DADA2 on merged reads, and I agree that usearch does a better job at assigning overlapped quality scores than seen in #434 

We still don't recommend it though.

**Comment by jianshu93** [comment]
NGmerge is much better than both pear and usearch https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2579-2
